import { ItemProp } from "./components/secondPoint/SecondPoint";
export const data1: ItemProp[] = [
  {
    img: "watch1.png",
    name: "Mazzucato",
    description: "Механические часы желтые",
    oldPrice: 7990,
    newPrice: 6990,
  },
  {
    img: "watch2.png",
    name: "Apple Watch 3",
    description: "Smart часы белые",
    oldPrice: 23990,
    newPrice: 20990,
  },
  {
    img: "watch3.png",
    name: "Samsung Watch",
    description: "Smart часы графитовые",
    oldPrice: 16990,
    newPrice: 14990,
  },
  {
    img: "watch4.png",
    name: "Zeppelin",
    description: "Классические часы металлика",
    oldPrice: 6990,
    newPrice: 5990,
  },
  {
    img: "watch5.png",
    name: "Stuhrling",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
  {
    img: "watch6.png",
    name: "Seiho",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
];
export const data2: ItemProp[] = [
  {
    img: "watch1.png",
    name: "Mazzucato",
    description: "Механические часы желтые",
    oldPrice: 7990,
    newPrice: 6990,
  },
  {
    img: "watch2.png",
    name: "Apple Watch 3",
    description: "Smart часы белые",
    oldPrice: 23990,
    newPrice: 20990,
  },
  {
    img: "watch3.png",
    name: "Samsung Watch",
    description: "Smart часы графитовые",
    oldPrice: 16990,
    newPrice: 14990,
  },
  {
    img: "watch4.png",
    name: "Zeppelin",
    description: "Классические часы металлика",
    oldPrice: 6990,
    newPrice: 5990,
  },
  {
    img: "watch5.png",
    name: "Stuhrling",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
  {
    img: "watch6.png",
    name: "Seiho",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
  {
    img: "watch1.png",
    name: "Mazzucato",
    description: "Механические часы желтые",
    oldPrice: 7990,
    newPrice: 6990,
  },
  {
    img: "watch2.png",
    name: "Apple Watch 3",
    description: "Smart часы белые",
    oldPrice: 23990,
    newPrice: 20990,
  },
  {
    img: "watch3.png",
    name: "Samsung Watch",
    description: "Smart часы графитовые",
    oldPrice: 16990,
    newPrice: 14990,
  },
  {
    img: "watch4.png",
    name: "Zeppelin",
    description: "Классические часы металлика",
    oldPrice: 6990,
    newPrice: 5990,
  },
  {
    img: "watch5.png",
    name: "Stuhrling",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
  {
    img: "watch6.png",
    name: "Seiho",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
  {
    img: "watch1.png",
    name: "Mazzucato",
    description: "Механические часы желтые",
    oldPrice: 7990,
    newPrice: 6990,
  },
  {
    img: "watch2.png",
    name: "Apple Watch 3",
    description: "Smart часы белые",
    oldPrice: 23990,
    newPrice: 20990,
  },
  {
    img: "watch3.png",
    name: "Samsung Watch",
    description: "Smart часы графитовые",
    oldPrice: 16990,
    newPrice: 14990,
  },
  {
    img: "watch4.png",
    name: "Zeppelin",
    description: "Классические часы металлика",
    oldPrice: 6990,
    newPrice: 5990,
  },
  {
    img: "watch5.png",
    name: "Stuhrling",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
  {
    img: "watch6.png",
    name: "Seiho",
    description: "Механические часы металлика",
    oldPrice: 9990,
    newPrice: 7990,
  },
  {
    img: "watch1.png",
    name: "Mazzucato",
    description: "Механические часы желтые",
    oldPrice: 7990,
    newPrice: 6990,
  },
  {
    img: "watch2.png",
    name: "Apple Watch 3",
    description: "Smart часы белые",
    oldPrice: 23990,
    newPrice: 20990,
  },
  {
    img: "watch3.png",
    name: "Samsung Watch",
    description: "Smart часы графитовые",
    oldPrice: 16990,
    newPrice: 14990,
  },
  {
    img: "watch4.png",
    name: "Zeppelin",
    description: "Классические часы металлика",
    oldPrice: 6990,
    newPrice: 5990,
  },
  {
    img: "watch3.png",
    name: "Samsung Watch",
    description: "Smart часы графитовые",
    oldPrice: 16990,
    newPrice: 14990,
  },
  {
    img: "watch4.png",
    name: "Zeppelin",
    description: "Классические часы металлика",
    oldPrice: 6990,
    newPrice: 5990,
  },
];
